import 'device.dart';
import 'package:flutter/material.dart';

final List<Device> devices = [
  Device(
    name: 'iPhone 12',
    type: 'iOS',
    osVersion: '16.6.1',
    serialNumber: '0000000001',
    color: 'Blue',
    storage: '128GB',
    imei: '000000000001',
    icon: Icons.phone_iphone,
    status: 'Active',
    department: 'DEP1',
  ),
  Device(
    name: 'iPhone 7 Plus',
    type: 'iOS',
    osVersion: '15.8.4',
    serialNumber: '0000000001',
    color: 'Red',
    storage: '128GB',
    imei: '000000000001',
    icon: Icons.phone_iphone,
    status: 'Inactive',
    department: 'DEP2',
  ),
  Device(
    name: 'iPhone 15 Pro',
    type: 'iOS',
    osVersion: '17.7',
    serialNumber: '0000000001',
    color: 'White',
    storage: '256GB',
    imei: '000000000001',
    icon: Icons.phone_iphone,
    status: 'Active',
    department: 'DEP1',
  ),
  Device(
    name: 'Samsung Galaxy S24',
    type: 'Android',
    osVersion: 'Android 14',
    serialNumber: '00001',
    color: 'Yellow',
    storage: '256GB',
    imei: '000001',
    icon: Icons.phone_android,
    status: 'Active',
    department: 'DEP3',
  ),
  Device(
    name: 'Samsung Galaxy A36 5G',
    type: 'Android',
    osVersion: 'Android 15',
    serialNumber: '00001',
    color: 'Black',
    storage: '256GB',
    imei: '000001',
    icon: Icons.phone_android,
    status: 'Inactive',
    department: 'DEP2',
  ),
  Device(
    name: 'Lenovo ThinkPad X12 Detachable Gen 2',
    type: 'Windows',
    osVersion: 'Windows 11',
    serialNumber: 'FP0001',
    color: 'Black',
    storage: '256GB SSD',
    processor: 'Intel Core Ultra 5 134U',
    ram: '16GB',
    icon: Icons.laptop,
    status: 'Active',
    department: 'DEP4',
  ),
  Device(
    name: 'Microsoft Surface Pro 7',
    type: 'Windows',
    osVersion: 'Windows 11',
    serialNumber: 'MS0001',
    color: 'Silver',
    storage: '256GB SSD',
    processor: 'i5-1034G7',
    ram: '8GB',
    icon: Icons.laptop,
    status: 'Inactive',
    department: 'DEP3',
  ),
  Device(
    name: 'iPhone 5c',
    type: 'iOS',
    osVersion: 'iOS 10.3.4',
    serialNumber: '0000000001',
    color: 'Green',
    storage: '16GB',
    imei: '000000000001',
    icon: Icons.phone_iphone,
    status: 'Inactive',
    department: 'DEP1',
  ),
]; 